### ISSUE TITLE
Have you tested it on any Sony devices?

### ISSUE THREAD

**Issue by oOJohn6Oo** [MarvL05/SonyUnlocker-BootLoader#1]

**Comment by MarvL05** [comment]
Well, never.
But I can promise you that it can work.
And I will upgrade it in next week.
BTW, how can you use it with Chinese?

**Comment by oOJohn6Oo** [comment]
" Chinese ???" What's the meaning? 
I am Chinese, and I have a Sony Xperia XZ2C, while it's Japan docomo version, and I'm finding a way to unlock the bootloader, that's why I'm here.

**Comment by MarvL05** [comment]
…所以大家都是中国人为什么不能直接用中文提issue呢

**Comment by oOJohn6Oo** [comment]
我不知道啊😂，想着英文稳妥些。这玩意能解`XZ2 Compact`吗？

**Comment by MarvL05** [comment]
有酷安吗，去搜索 铭灏MarvL05，翻一翻图文，有出过教程

**Comment by oOJohn6Oo** [comment]
不好意思没看代码，我的意图是直接把 `status: No` 改为`status: Yes`。打扰了。
